// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  winners_page: string;
  winners_page_title: string;
}
export const cssExports: CssExports;
export default cssExports;
