// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header_wrapper': string;
  'header_wrapper_buttons': string;
  'header_wrapper_title': string;
}
export const cssExports: CssExports;
export default cssExports;
