// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  disabled: string;
  next: string;
  pagination: string;
  paginationItem: string;
  post: string;
  prev: string;
}
export const cssExports: CssExports;
export default cssExports;
