// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button_controller_bottom': string;
  'button_controller_top': string;
  'buttons_controller': string;
}
export const cssExports: CssExports;
export default cssExports;
