// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  car_race_block: string;
  icon_container: string;
}
export const cssExports: CssExports;
export default cssExports;
