// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  race_functionality_container: string;
}
export const cssExports: CssExports;
export default cssExports;
